
name: commit
on:
  release:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - run: chmod 777 Dockerfile
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@master
        with:
          commit_prefix: "[AUTO-COMMIT] replace"
      - name: Create pull request
        uses: devops-infra/action-pull-request@master
        with:
          body: "**Automated pull request**<br><br>Replaced foo/bar"
          title: ${{ github.event.commits[0].message }}
