
name: commit
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - run: |
              chmod 777 Dockerfile
              git config --global user.name 'orezl'
              git config --global user.email 'rahulkhanna2910@gmail.com'
              git commit -am "Automated report"
              git push
      
