
name: commit
on:
  push:
    branches: [ main ]
    paths-ignore: ['.github/**']
  release:
    types: [released, prereleased]
  workflow_dispatch:
    inputs:
      build_stage: {required: true, type: choice, description: "Build stage", options: [ 'dv', 'qa', 'pd' ] }
jobs: 
  Matrix_setup:
    runs-on: ubuntu-latest
    outputs:
      stages: ${{steps.set.outputs.stages}}
    steps:
      - uses: actions/checkout@v2
      - id: 'set'
        #run: echo "::set-output name=stages::['dv']"
        run: echo "stages=['dv','qa']" >> $GITHUB_OUTPUT
      - run: echo "${{steps.set.outputs.stages}}"
  commit:
    name: ${{matrix.aws_account}}_Stage 
    needs: Matrix_setup
    strategy:
      matrix:
        aws_account: [EV1, EV1]
        stages: ${{fromJson(needs.Matrix_setup.outputs.stages)}}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - run: |
              env    
              echo "event name is:" ${{ github.event_name }} 
              echo "event type is:" ${{ github.event.action }}
              echo "event type is:" ${{ github.event_action }}
              #cat .github/workflows/commit.yml
              #chmod 777 test.sh
              #git config --global user.name 'orezl'
              #git config --global user.email 'rahulkhanna2910@gmail.com'
              #git commit -am "Automated report"
              #git push
      
#v1.0.0-rc.3
