name: cd-qa
on:
  release:
    types: [released]
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - run: env
      - name: Check out code
        uses: actions/checkout@v2
#      - name: Install yq
#        id: setup-yq
#        uses: shiipou/setup-yq-action@v2.0.1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::433213351671:role/iam_role
          role-session-name: MySessionName
          role-duration-seconds: 1200
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: 433213351671.dkr.ecr.ap-northeast-1.amazonaws.com
          ECR_REPOSITORY: test
          IMAGE_TAG: v2.3.4
        run: |
              MANIFEST=$(aws ecr batch-get-image --registry-id 433213351671 --repository-name "$ECR_REPOSITORY" --image-ids imageTag=v2-rc.1 --output json | jq --raw-output --join-output '.images[0].imageManifest')
              aws ecr put-image --registry-id 433213351671 --repository-name "$ECR_REPOSITORY" --image-tag "$IMAGE_TAG" --image-manifest "$MANIFEST"
#          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_REF_NAME .
#          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_REF_NAME
