name: testing
on:
  push:
    branches: ['main']
    paths-ignore: ['.github/**']
  workflow_dispatch:
      inputs:
        version: {required: true, description: "version"}
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - run: |
              echo "${sha}"
              echo "${ref}"
              echo "${action}"
        env:
          sha: ${{ env.GITHUB_SHA || inputs.version }} 
          ref: ${{ inputs.version || env.GITHUB_REF_NAME }}
          action: ${{ env.github.event.action }}
      - name: Check out code
        uses: actions/checkout@v2
#      - name: Install yq
#        id: setup-yq
#        uses: shiipou/setup-yq-action@v2.0.1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::433213351671:role/iam_role
          role-session-name: MySessionName
          role-duration-seconds: 1200
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - name: Install dependencies
        run: pip install boto3
      - name: Check build stage, release_point_ref and set entrypoint environment
        id: 'workflow_call_inputs_setup'
        run: |
              cd simple-reactjs-app
              npm install
              npm run build
              cd ..
              python upload.py ${GITHUB_WORKSPACE}
