name: cd-qa
on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
      image_version: {required: true, description: "Pre-release published image version"}
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - run: env
      - name: Check out code
        uses: actions/checkout@v2
#      - name: Install yq
#        id: setup-yq
#        uses: shiipou/setup-yq-action@v2.0.1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::433213351671:role/iam_role
          role-session-name: MySessionName
          role-duration-seconds: 1200
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: 433213351671.dkr.ecr.ap-northeast-1.amazonaws.com
          ECR_REPOSITORY: test
          #IMAGE_TAG: ${{ env.GITHUB_SHA }}
        run: |
          chmod 777 Dockerfile
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_REF_NAME .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_REF_NAME
